api.openweathermap.org/data/2.5/weather?lat=10.823099&lon=10.823099&appid=605e3a1594b5b4bf8d358f3b01d830dd&units=metric&lang=vi

################################
api.openweathermap.org/data/2.5/weather?q=ho chi minh&appid=605e3a1594b5b4bf8d358f3b01d830dd&units=metric&lang=vi